zachary:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 5000 # 限制Redis客户端等待响应的最长时间。如果超过这个时间还没有收到服务器的响应，会抛出超时异常
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
