spring:
  redis:
    host: ${zachary.redis.host}
    port: ${zachary.redis.port}
    password: ${zachary.redis.password}
    database: ${zachary.redis.database}
    timeout: ${zachary.redis.timeout}
    lettuce:
      pool:
        max-active: ${zachary.redis.lettuce.pool.max-active}
        max-idle: ${zachary.redis.lettuce.pool.max-idle}
        min-idle:  ${zachary.redis.lettuce.pool.min-idle}
